{
 "title": "tengine",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "error rate in passed 5m",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((nginx_http_4xx + nginx_http_5xx) / nginx_req_total) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "web status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "server_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "web error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nginx_http_ups_5xx", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nginx_accepted_connections - nginx_handled_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request time avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "nginx_request_time / nginx_req_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "nginx_http_4xx", "legendFormat": "__auto" },
    { "expr": "nginx_http_5xx", "legendFormat": "__auto" },
    { "expr": "nginx_http_2xx", "legendFormat": "__auto" },
    { "expr": "nginx_http_3xx", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "nginx_active_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "writing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "nginx_writing_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "nginx_req_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "nginx_waiting_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "reading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    { "expr": "nginx_reading_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "handled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    { "expr": "nginx_handled_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "accepts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    { "expr": "nginx_accepted_connections", "legendFormat": "__auto" }
   ]
  }
 ]
}